engines:
  brakeman:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
exclude_paths:
- spec/
- vendor/asset
