inherits_from: .haml-lint_todo.yml

# Whether to ignore frontmatter at the beginning of HAML documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: false

exclude:
  - 'vendor/**/*'
  - 'spec/**/*'
  - 'lib/templates/**/*'
  - 'app/views/kaminari/**/*'
