language: ruby
cache: bundler

notifications:
  email: false

env:
  matrix:
    - TRAVIS_NODE_VERSION="4"
  global:
    - LOCAL_DOMAIN=cb6e6126.ngrok.io
    - LOCAL_HTTPS=true
    - RAILS_ENV=test

addons:
  postgresql: 9.4

rvm:
  - 2.3.1

services:
  - redis-server

bundler_args: --without development production --retry=3 --jobs=3

install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g npm@3
  - npm install -g yarn
  - bundle install
  - yarn install

before_script:
  - bundle exec rails db:create db:migrate

script:
  - bundle exec rspec
  - npm test
