version: '3'
services:

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    networks:
      - external_network
      - internal_network
    volumes:
    - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
    - ./data/redis:/data


  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
        RAILS_ENV: "development"
        NODE_ENV: "development"
        BUNDLE_WITHOUT: ""

    image: catgram-dev
    env_file: .env.development
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - ".:/opt/mastodon"
    networks:
      - external_network
      - internal_network
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
      - redis
      - prometheus_exporter

  streaming:
    image: catgram-dev
    env_file: .env.development
    command: yarn start
    volumes:
    - ".:/opt/mastodon"
    ports:
      - "4000:4000"
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis

  sidekiq:
    image: catgram-dev
    env_file: .env.development
    command: bundle exec sidekiq
    networks:
      - external_network
      - internal_network
    volumes:
    - ".:/opt/mastodon"
    depends_on:
      - db
      - redis

  prometheus_exporter:
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/prometheus_exporter:latest
    ports:
      - "9394:9394"
    networks:
      - external_network

networks:
  external_network:
  internal_network:
    internal: true
