version: '3'
services:

  db:
    image: postgres:9.6-alpine
    volumes:
    - /var/lib/postgresql/data
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  redis:
    restart: always
    image: redis:5.0-alpine
    volumes:
    - /var/data/docker-data/catgram-redis:/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000

    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/catgram
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
      - prometheus_exporter
#      - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    build:
      context: .
      dockerfile: Dockerfile
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/catgram
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/catgram
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system


  prometheus_exporter:
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/prometheus_exporter:latest
    ports:
      - "9394:9394"
    networks:
      - external_network

## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
