version: '3'
services:

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    networks:
      - external_network
      - internal_network
    volumes:
    - /var/data/docker-data/catgram-postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
    - /var/data/docker-data/catgram-redis:/data

  web:
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/catgram
    env_file: .env.development
    command: /mastodon/boot_dev.sh web
    volumes:
    - ".:/mastodon"
    networks:
      - external_network
      - internal_network
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
      - redis
      - prometheus_exporter

  streaming:
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/catgram
    env_file: .env.development
    command: /mastodon/boot_dev.sh streaming
    volumes:
    - ".:/mastodon"
    ports:
      - "4000:4000"
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis

  sidekiq:
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/catgram
    env_file: .env.development
    command: /mastodon/boot_dev.sh sidekiq
    networks:
      - external_network
      - internal_network
    volumes:
    - ".:/mastodon"
    depends_on:
      - db
      - redis

  prometheus_exporter:
    image: 563848776164.dkr.ecr.us-west-2.amazonaws.com/prometheus_exporter:latest
    ports:
      - "9394:9394"
    networks:
      - external_network

networks:
  external_network:
  internal_network:
    internal: true
