version: '2'
services:

  db:
    restart: always
    image: postgres:alpine
### Uncomment to enable DB persistance
    volumes:
      - ./../../home/mastodon/postgresql/data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
### Uncomment to enable REDIS persistance
    volumes:
      - ./redis:/data

  web:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq1:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -c 40 -q default 
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  sidekiq2:
    restart: always
    build: .
    image: gargron/mastodon
    env_file: .env.production
    command: bundle exec sidekiq -c 5 -q mailers
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  sidekiq3:
    restart: always
    build: .
    image: gargron/mastodon
    env_file: .env.production
    command: bundle exec sidekiq -c 10 -q pull
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  sidekiq4:
    restart: always
    build: .
    image: gargron/mastodon
    command: bundle exec sidekiq -c 15 -q push
    env_file: .env.production
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  sidekiq5:
    restart: always
    build: .
    image: gargron/mastodon
    env_file: .env.production
    command: bundle exec sidekiq -c 40 -q default 
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

#  sidekiq6:
#    restart: always
#    build: .
#    env_file: .env.production
#    command: bundle exec sidekiq -c 20 -q default 
#    depends_on:
#      - db
#      - redis
#    volumes:
#      - ./public/system:/mastodon/public/system
