services:
  - type: web
    name: toot-pizza-web
    region: ohio
    env: docker
    plan: standard
    domains:
      - toot.pizza
    repo: https://github.com/irubnich/toot-pizza.git
    branch: render
    pullRequestPreviewsEnabled: true
    dockerfilePath: ./deploy/Dockerfile.web
    dockerContext: ./deploy
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - fromGroup: toot-pizza
      - key: PORT
        value: 3000
