name: 'Setup RUby'
description: 'Setup a Ruby environment ready to run the Mastodon code'
inputs:
  ruby-version:
    description: The Ruby version to install
    default: '.ruby-version'
  additional-system-dependencies:
    description: 'Additional packages to install'

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libicu-dev libidn11-dev ${{ inputs.additional-system-dependencies }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: false

    - run: bundle update stringio

    - uses: actions/cache@v4
      with:
        path: ./vendor/bundle
        key: ${{ runner.os }}-${{ inputs.ruby-version }}-gems-${{ github.ref }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.ruby-version }}-gems-${{ github.ref }}
          ${{ runner.os }}-${{ inputs.ruby-version }}-gems-master
          ${{ runner.os }}-${{ inputs.ruby-version }}-gems-

    - name: bundle install
      run: |
        bundle config --local path $PWD/vendor/bundle
        bundle config --local deployment true
        bundle install --jobs 4 --retry 3
        bundle clean
