---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mastodon.fullname" . }}-assets
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.assets.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    {{- toYaml .Values.persistence.assets.resources | nindent 4}}
  storageClassName: {{ .Values.persistence.assets.storageClassName }}
