apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "assets-volume"
