default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
elephant: styles/elephant-dark.scss
elephant-contrast: styles/elephant-contrast.scss
elephant-light: styles/elephant-light.scss
