default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
elephant: styles/mastodon-bird-ui-dark.scss
elephant-contrast: styles/mastodon-bird-ui-contrast.scss
elephant-light: styles/mastodon-bird-ui-light.scss
