# Publish the mastdodon helm chart to mastodon.github.io/mastodon as a .tgz file.
# helm/chart-releaser-action will push an index.yaml file to the gh-pages branch with a reference to the .tgz file.
# The tgz file is stored as a release asset in github.
name: Publish helm chart

concurrency: release-helm

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  release:
    # Write permission is required to write to the gh-pages branch.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update chart dependencies
        run: |
          helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          helm dependency build charts/mastodon

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"  # if a release already exists for the version, don't try to upload it again
